# Generated by Django 5.2.7 on 2025-11-09 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_wash', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('total_price', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Final total price')),
                ('status', models.CharField(choices=[('en_route', 'En Route'), ('on_site', 'On Site'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='en_route', verbose_name='Status')),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.box', verbose_name='Box')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.car', verbose_name='Car')),
                ('car_wash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.carwash', verbose_name='Car wash')),
                ('services', models.ManyToManyField(related_name='orders', to='services.services', verbose_name='Services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('washer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Washer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
