# Generated by Django 5.2.8 on 2026-02-12 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_wash', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('total_price', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Final total price')),
                ('duration', models.DurationField(verbose_name='Total duration')),
                ('status', models.CharField(choices=[('en_route', 'En Route'), ('on_site', 'On Site'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='en_route', verbose_name='Status')),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.box', verbose_name='Box')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.car', verbose_name='Car')),
                ('car_wash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.carwash', verbose_name='Car wash')),
                ('services', models.ManyToManyField(related_name='orders', to='services.services', verbose_name='Services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('washer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Washer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(help_text='Lower number means earlier in queue', verbose_name='Position in Queue')),
                ('expected_start_time', models.DateTimeField(verbose_name='Expected Start Time')),
                ('expected_duration', models.DurationField(blank=True, null=True, verbose_name='Expected Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='car_wash.carwash', verbose_name='Car Wash')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='orders.orders', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Queue Entry',
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', '-created_at'], name='ord_cw_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', 'status', '-created_at'], name='ord_cw_status_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car', '-created_at'], name='ord_car_created_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', 'user', '-created_at'], name='ord_cw_user_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['car_wash', 'position'], name='orders_queu_car_was_e0f593_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['order'], name='orders_queu_order_i_1a8cef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queueentry',
            unique_together={('car_wash', 'position')},
        ),
    ]
