# Generated by Django 5.2.8 on 2025-12-09 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0003_alter_cartype_id_car_car_number_idx'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', '-created_at'], name='ord_cw_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', 'status', '-created_at'], name='ord_cw_status_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car', '-created_at'], name='ord_car_created_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['car_wash', 'user', '-created_at'], name='ord_cw_user_created_desc_idx'),
        ),
    ]
