# Generated by Django 5.2.7 on 2025-10-26 12:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Data')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Car Wash',
                'verbose_name_plural': 'Car Washes',
            },
        ),
        migrations.CreateModel(
            name='CarWashDocuments',
            fields=[
                ('car_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='carwash.carwash', verbose_name='CarWash')),
                ('iin', models.CharField(max_length=12, verbose_name='TOO/IIN')),
            ],
            options={
                'verbose_name': 'Car Wash Documents',
            },
        ),
        migrations.CreateModel(
            name='CarWashSettings',
            fields=[
                ('car_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='carwash.carwash', verbose_name='CarWash')),
                ('opens_at', models.TimeField(default='9:00', verbose_name='Opens at')),
                ('closes_at', models.TimeField(default='21:00', verbose_name='Closes at')),
                ('percent_washers', models.IntegerField(blank=True, default=30, verbose_name='Washer Percent')),
                ('car_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=20)),
            ],
            options={
                'verbose_name': 'Car Wash Settings',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'number'], name='carwash_car_owner_i_8ec1d3_idx')],
                'unique_together': {('owner', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['owner'], name='carwash_car_owner_i_5e5d0b_idx'),
        ),
    ]
