# Generated by Django 4.1.5 on 2023-08-06 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('inn', models.CharField(max_length=12, verbose_name='TOO/INN')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('start_time', models.TimeField(max_length=15, verbose_name='Start Time')),
                ('end_time', models.TimeField(max_length=20, verbose_name='End time')),
                ('slots', models.PositiveIntegerField(verbose_name='Slots')),
                ('img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='Time end last order')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date create')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Soft delete')),
                ('is_validate', models.BooleanField(default=False, verbose_name='Is validate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_wash', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'CarWash',
                'verbose_name_plural': 'CarWashes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.CharField(max_length=40, verbose_name='Description')),
                ('type_auto', models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Minivan', 'Minivan')], max_length=15, verbose_name='Number Auto')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('time_work', models.PositiveSmallIntegerField(help_text='В минутах', verbose_name='Time work')),
                ('extra', models.BooleanField(default=False, verbose_name='Extra Service')),
                ('wash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='app_washes.carwash', verbose_name='Car Wash')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date create')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_rating', to='app_washes.carwash', verbose_name='Car Wash')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='CarWashCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=255, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, max_length=255, verbose_name='Longitude')),
                ('wash', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wash_coordinates', to='app_washes.carwash', verbose_name='Car Wash')),
            ],
            options={
                'verbose_name': 'Car Wash Coordinates',
                'verbose_name_plural': 'Car Wash Coordinates',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_boss', to=settings.AUTH_USER_MODEL)),
                ('wash', models.ManyToManyField(related_name='wash_admin', to='app_washes.carwash', verbose_name='Car Wash')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
        ),
    ]
