# Generated by Django 4.1.5 on 2023-08-10 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='date_create',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='last_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Time end last order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date create'),
        ),
    ]
