# Generated by Django 4.1.5 on 2023-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0002_alter_carwash_date_create_alter_carwash_last_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date create'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time end last order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date create'),
        ),
    ]
