# Generated by Django 4.1.5 on 2023-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0003_alter_carwash_date_create_alter_carwash_last_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
