# Generated by Django 4.1.5 on 2023-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0004_carwash_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type_auto',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus')], max_length=15, verbose_name='Number Auto'),
        ),
    ]
