# Generated by Django 4.1.5 on 2023-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0005_alter_service_type_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Description'),
        ),
    ]
