# Generated by Django 4.1.5 on 2023-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0006_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='address',
            field=models.CharField(max_length=60, verbose_name='Address'),
        ),
    ]
