# Generated by Django 4.1.5 on 2024-03-24 09:16

import app_washes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0008_alter_carwash_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='url_2gis',
            field=models.CharField(blank=True, max_length=256, null=True, validators=[app_washes.models.validate_url]),
        ),
    ]
