# Generated by Django 4.1.5 on 2024-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0009_carwash_url_2gis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwash',
            old_name='url_2gis',
            new_name='link_2_gis',
        ),
    ]
