# Generated by Django 4.1.5 on 2025-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0010_rename_url_2gis_carwash_link_2_gis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
            },
        ),
    ]
