# Generated by Django 4.1.5 on 2025-07-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0011_washer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
    ]
