# Generated by Django 4.1.5 on 2025-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0012_remove_administrator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='percent_washers',
            field=models.IntegerField(blank=True, choices=[(30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')], default=30, verbose_name='Percent Washers'),
        ),
    ]
