# Generated by Django 4.1.5 on 2025-08-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_washes', '0013_carwash_percent_washers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL),
        ),
    ]
