# Generated by Django 4.1.5 on 2025-08-28 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_washes', '0014_alter_administrator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone',
            field=models.ForeignKey(db_column='user_phone', on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL, to_field='phone'),
        ),
    ]
