"""
Django settings for iLine project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = environ.Path(__file__) - 2

# Load environment variables from .env files if present
load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.environ.get("DEBUG", "0").lower() in ("1", "true", "yes", "on")

APP_HOST = os.environ.get('APP_HOST', 'http://localhost:8000/')

ALLOWED_HOSTS = os.environ["DJANGO_ALLOWED_HOSTS"].split(',')

# Application definition

INSTALLED_APPS = [
    'admin_tools_stats',
    'django_nvd3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'allauth.usersessions',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'django_attribution',
    'django_admin_listfilter_dropdown',
    'accounts.apps.AccountsConfig',
    'car_wash.apps.CarwashConfig',
    'services.apps.ServicesConfig',
    'orders.apps.OrdersConfig',
    'marketing.apps.MarketingConfig',
    'rating.apps.RatingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'iLine.middleware.SessionTokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_attribution.middlewares.TrackingParameterMiddleware",
    "django_attribution.middlewares.AttributionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         # For each OAuth based provider, either add a ``SocialApp``
#         # (``socialaccount`` app) containing the required client
#         # credentials, or list them here:
#         'APP': {
#             'client_id': '123',
#             'secret': '456',
#             'key': ''
#         }
#     }
# }

ACCOUNT_LOGIN_METHODS = {"phone"}

ACCOUNT_SIGNUP_FIELDS = [
  'phone*', 'password1*', 'username*'
]
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_PHONE_VERIFICATION_TIMEOUT = 300
ACCOUNT_PHONE_VERIFICATION_SUPPORTS_RESEND = True
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = 'email'  # for bot protection

HEADLESS_ADAPTER = 'accounts.adapters.HeadlessAdapter'
HEADLESS_ONLY = True
HEADLESS_SERVE_SPECIFICATION = True

SITE_ID = int(os.environ.get('SITE_ID', 1))

# Media files
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(str(BASE_DIR), 'media'))

ACCOUNT_UNIQUE_USERNAME = False
ACCOUNT_USER_MODEL_EMAIL_FIELD = None

# Time and localization
TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')
USE_TZ = True

# Celery configuration (uses django-environ with CELERY_ namespace)
# Broker/Backend: default to Redis service in docker-compose; override via env in other envs
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Run tasks eagerly in DEBUG if explicitly requested (useful for local dev without broker)
CELERY_TASK_ALWAYS_EAGER = bool(os.environ.get('CELERY_TASK_ALWAYS_EAGER', False))

DJANGO_ATTRIBUTION = {
    'SOURCE_OBJECT_ID_FIELD': 'UUIDField',
    'CURRENCY': 'KZT',

    # Skip tracking utm params on these URLs
    'UTM_EXCLUDED_URLS': [
        '/admin/',
    ],
}

ROOT_URLCONF = 'iLine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'iLine.wsgi.application'

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000').split(',')

if DEBUG:
    # CSRF and session cookie settings suitable for local development
    # CSRF_COOKIE_SECURE = False
    # SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
else:
    CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN')
    SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN')

CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = os.environ.get('CSRF_COOKIE_HTTPONLY', 'False').lower() in ('1','true','yes','on')  # Allow JavaScript to read the cookie by default; override via env for stricter security
CSRF_COOKIE_NAME = 'csrftoken'  # Explicitly set the cookie name
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': int(os.environ.get('POSTGRES_PORT', 5432)),
    }
}

REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'I-Line API',
    'DESCRIPTION': 'Online car wash queue application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


# Static files (CSS, JavaScript, Images)
# Keep minimal: in DEBUG, Django will serve app static automatically; no collectstatic in production.
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(str(BASE_DIR), 'staticfiles'))

# Security & proxy settings for production
if not DEBUG:
    # Assume app is behind a reverse proxy/ingress that terminates TLS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    # Cookies over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (can be tuned via env SECURE_HSTS_SECONDS)
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # SECURE_BROWSER_XSS_FILTER was removed in newer Django; modern browsers handle XSS protection
else:
    # Development conveniences
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False

# Logging: console plus daily-rotated files kept for the last 7 days
# In production, file logging is enabled ONLY if DJANGO_LOG_DIR is provided.
# In DEBUG, default to BASE_DIR/logs for developer convenience.
LOG_DIR = os.environ.get('DJANGO_LOG_DIR') or (os.path.join(str(BASE_DIR), 'logs') if DEBUG else None)
if LOG_DIR:
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
    except Exception:
        # If directory can't be created (e.g., read-only FS), fall back to console-only
        LOG_DIR = None

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
        },
        'simple': {
            'format': '%(levelname)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        **({
            'app_file': {
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': os.path.join(LOG_DIR, 'app.log'),
                'when': 'midnight',
                'backupCount': 7,
                'encoding': 'utf-8',
                'utc': True,
            },
            'django_file': {
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': os.path.join(LOG_DIR, 'django.log'),
                'when': 'midnight',
                'backupCount': 7,
                'encoding': 'utf-8',
                'utc': True,
            },
        } if LOG_DIR else {})
    },
    'root': {
        'handlers': ['console'] + (['app_file'] if LOG_DIR else []),
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'] + (['django_file'] if LOG_DIR else []),
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO'),
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use custom user model
AUTH_USER_MODEL = 'accounts.User'

# Kafka configuration
KAFKA_BOOTSTRAP_SERVERS = os.environ.get('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')
KAFKA_SMS_TOPIC = os.environ.get('KAFKA_SMS_TOPIC', 'sms')
KAFKA_TELEGRAM_TOPIC = os.environ.get('KAFKA_TELEGRAM_TOPIC', 'telegram')
KAFKA_WHATSAPP_TOPIC = os.environ.get('KAFKA_WHATSAPP_TOPIC', 'whatsapp')
