# Generated by Django 5.2.7 on 2025-10-30 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.TimeField()),
                ('is_extra', models.BooleanField(default=False)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car_wash.cartypes')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car_wash.carwash')),
            ],
            options={
                'verbose_name': 'Service',
                'indexes': [models.Index(fields=['car_wash'], name='services_se_car_was_dd6f0b_idx')],
            },
        ),
    ]
