# Generated by Django 5.2.8 on 2026-02-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='review',
        ),
    ]
