# Generated by Django 4.1.5 on 2023-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotsInWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Free', 'Free'), ('Reserve', 'Reserve'), ('On site', 'On site'), ('In progress', 'In progress'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Free', max_length=20, null=True)),
            ],
        ),
    ]
