# Generated by Django 4.1.5 on 2023-08-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_adminwork', '0001_initial'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotsinwash',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='app_orders.order'),
        ),
    ]
