# Generated by Django 4.1.5 on 2023-08-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_adminwork', '0002_initial'),
        ('app_washes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotsinwash',
            name='wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='app_washes.carwash'),
        ),
    ]
