MAX_USERNAME_LENGTH = 100
MIN_PHONE_NUMBER_LENGTH = 12
MAX_PHONE_NUMBER_LENGTH = 15
SMS_CODE_LENGTH = 4

MIN_SMS_CODE_VALUE = 10 ** (SMS_CODE_LENGTH - 1)
MAX_SMS_CODE_VALUE = 10 ** SMS_CODE_LENGTH - 1