# Generated by Django 5.2.7 on 2025-11-02 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Data')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('managers', models.ManyToManyField(related_name='manager_car_washes', related_query_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Managers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_car_washes', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('washers', models.ManyToManyField(related_name='washer_car_washes', related_query_name='washers', to=settings.AUTH_USER_MODEL, verbose_name='Washers')),
            ],
            options={
                'verbose_name': 'Car Wash',
                'verbose_name_plural': 'Car Washes',
            },
        ),
        migrations.CreateModel(
            name='CarWashDocuments',
            fields=[
                ('car_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='car_wash.carwash', verbose_name='CarWash')),
                ('iin', models.CharField(max_length=12, verbose_name='TOO/IIN')),
            ],
            options={
                'verbose_name': 'Car Wash Documents',
            },
        ),
        migrations.CreateModel(
            name='CarWashSettings',
            fields=[
                ('car_wash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='car_wash.carwash', verbose_name='CarWash')),
                ('opens_at', models.TimeField(default='9:00', verbose_name='Opens at')),
                ('closes_at', models.TimeField(default='21:00', verbose_name='Closes at')),
                ('percent_washers', models.IntegerField(blank=True, default=30, verbose_name='Washer Percent')),
            ],
            options={
                'verbose_name': 'Car Wash Settings',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Box', max_length=100)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='car_wash.carwash')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Registration plate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'number'], name='car_wash_ca_owner_i_fce2d2_idx')],
                'unique_together': {('owner', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='Car type')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_types', to='car_wash.carwashsettings')),
            ],
        ),
        migrations.AddIndex(
            model_name='carwash',
            index=models.Index(fields=['owner'], name='car_wash_ca_owner_i_1187fe_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['car_wash'], name='car_wash_bo_car_was_558d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartypes',
            index=models.Index(fields=['settings'], name='car_wash_ca_setting_aaa0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartypes',
            unique_together={('settings', 'name')},
        ),
    ]
