# Generated by Django 5.2.8 on 2025-12-07 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='carwashsettings',
            name='percent_washers',
            field=models.IntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(35)], verbose_name='Washer Percent'),
        ),
    ]
