# Generated by Django 5.2.7 on 2025-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(default='Box', max_length=100),
        ),
    ]
