# Generated by Django 5.2.7 on 2025-10-31 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='managers',
            field=models.ManyToManyField(related_name='manager_car_washes', related_query_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='washers',
            field=models.ManyToManyField(related_name='washer_car_washes', related_query_name='washers', to=settings.AUTH_USER_MODEL, verbose_name='Washers'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_car_washes', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
