# Generated by Django 5.2.8 on 2026-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Car type'),
        ),
    ]
