# Generated by Django 5.2.8 on 2026-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_cartype_description_alter_cartype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='car_wash_logos/', verbose_name='Logo'),
        ),
    ]
