# Generated by Django 5.2.8 on 2025-12-09 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_carwash_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['number'], name='car_number_idx'),
        ),
    ]
