# Generated by Django 5.2.7 on 2025-10-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_box_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashsettings',
            name='car_types',
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Registration plate'),
        ),
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Car type')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_types', to='car_wash.carwashsettings')),
            ],
            options={
                'indexes': [models.Index(fields=['settings'], name='car_wash_ca_setting_aaa0d3_idx')],
                'unique_together': {('settings', 'name')},
            },
        ),
    ]
