# Generated by Django 5.2.8 on 2026-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0003_carwash_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashdocuments',
            name='legal_address',
            field=models.CharField(default='', max_length=500, verbose_name='Legal Address'),
            preserve_default=False,
        ),
    ]
