# Generated by Django 5.2.8 on 2026-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0004_carwashdocuments_legal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashdocuments',
            name='legal_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='carwashdocuments',
            name='iin',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='IIN/BIN'),
        ),
        migrations.AlterField(
            model_name='carwashdocuments',
            name='legal_address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Legal Address'),
        ),
    ]
