# Generated by Django 5.2.8 on 2026-02-12 05:47

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Campaign name')),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), default=list, size=None)),
                ('medium', models.CharField(max_length=31)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
    ]
