# Generated by Django 4.1.5 on 2023-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(fields=('user', 'last_number'), name='unique_user_number'),
        ),
    ]
