# Generated by Django 4.1.5 on 2023-08-10 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_bankcard_unique_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date create'),
        ),
    ]
