# Generated by Django 4.1.5 on 2023-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_user_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date create'),
        ),
    ]
