# Generated by Django 4.1.5 on 2023-08-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_user_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_orders', models.PositiveSmallIntegerField()),
                ('sum', models.IntegerField(verbose_name='Payout amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_cashout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
