# Generated by Django 4.1.5 on 2023-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_usercodeconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercodeconfirm',
            name='user',
            field=models.CharField(blank=True, max_length=30, verbose_name='Full name'),
        ),
    ]
