# Generated by Django 4.1.5 on 2023-08-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_usercodeconfirm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercodeconfirm',
            name='user',
        ),
    ]
