# Generated by Django 4.1.5 on 2023-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_remove_usercodeconfirm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutdata',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_auto',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus')], max_length=15, verbose_name='Number Auto'),
        ),
    ]
