# Generated by Django 4.1.5 on 2023-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_cashoutdata_date_create_alter_user_type_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutdata',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payout amount'),
        ),
    ]
