# Generated by Django 4.1.5 on 2024-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_alter_cashoutdata_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutdata',
            name='list_order',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
