# Generated by Django 4.1.5 on 2024-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_cashoutdata_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id_telegram',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Chat ID in Telegram'),
        ),
    ]
