# Generated by Django 4.1.5 on 2024-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_alter_user_chat_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id_telegram',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Chat ID in Telegram'),
        ),
    ]
