# Generated by Django 4.1.5 on 2023-08-06 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Item Service',
                'verbose_name_plural': 'Items Service',
            },
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=355)),
                ('datecreate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Time start')),
                ('time_work', models.PositiveSmallIntegerField(blank=True, help_text='В минутах', null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Time end')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='Final price')),
                ('commission', models.IntegerField(blank=True, null=True, verbose_name='Commission')),
                ('status', models.CharField(blank=True, choices=[('Free', 'Free'), ('Reserve', 'Reserve'), ('On site', 'On site'), ('In progress', 'In progress'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Reserve', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Created', 'Created'), ('InProgress', 'InProgress'), ('Fulfilled', 'Fulfilled'), ('Timeout', 'Timeout'), ('Reject', 'Reject'), ('Canceled', 'Canceled')], default='Pending', max_length=20, verbose_name='Status')),
                ('on_site', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='On site or on the road')),
                ('rating', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('rated', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Evaluation status')),
                ('notified', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Evaluation status')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date time order create')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Soft delete')),
                ('test_field', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=155)),
                ('price', models.CharField(max_length=155)),
                ('id_payment', models.CharField(max_length=155)),
                ('commission', models.CharField(max_length=155)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Created', 'Created'), ('InProgress', 'InProgress'), ('Fulfilled', 'Fulfilled'), ('Timeout', 'Timeout'), ('Reject', 'Reject'), ('Canceled', 'Canceled')], default='Pending', max_length=20, verbose_name='Status')),
                ('type_payment', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Type payment')),
                ('status', models.CharField(max_length=255)),
                ('err', models.CharField(blank=True, max_length=255, null=True)),
                ('err_code', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
