# Generated by Django 4.1.5 on 2023-08-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_washes', '0001_initial'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_washes.carwash', verbose_name='CarWash'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_customer', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(through='app_orders.ItemService', to='app_washes.service'),
        ),
        migrations.AddField(
            model_name='itemservice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_service', to='app_orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='itemservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_washes.service', verbose_name='Service'),
        ),
    ]
