# Generated by Django 4.1.5 on 2023-08-23 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_out_status',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Evaluation status'),
        ),
    ]
