# Generated by Django 4.1.5 on 2023-08-26 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_order_cash_out_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_out_status',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Evaluation status'),
        ),
    ]
