# Generated by Django 4.1.5 on 2023-08-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_alter_order_cash_out_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='order',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
