# Generated by Django 4.1.5 on 2023-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_alter_paymentdata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Created', 'Created'), ('Sent', 'Sent'), ('InProgress', 'InProgress'), ('Fulfilled', 'Fulfilled'), ('Timeout', 'Timeout'), ('Reject', 'Reject'), ('Canceled', 'Canceled')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Created', 'Created'), ('Sent', 'Sent'), ('InProgress', 'InProgress'), ('Fulfilled', 'Fulfilled'), ('Timeout', 'Timeout'), ('Reject', 'Reject'), ('Canceled', 'Canceled')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
