# Generated by Django 4.1.5 on 2024-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_alter_paymentdata_commission_alter_paymentdata_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCallbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=55)),
                ('callback', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_cashout_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
