# Generated by Django 4.1.5 on 2024-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0008_fullcallbackdata_order_payment_cashout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcallbackdata',
            name='type_callback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fullcallbackdata',
            name='order',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
