# Generated by Django 4.1.5 on 2024-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0009_fullcallbackdata_type_callback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='metadata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
