# Generated by Django 4.1.5 on 2024-02-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0010_alter_paymentdata_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdata',
            name='metadata',
        ),
    ]
