# Generated by Django 4.1.5 on 2024-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0011_remove_paymentdata_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
