# Generated by Django 4.1.5 on 2024-03-09 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0012_paymentdata_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_by_admin',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Evaluation status'),
        ),
    ]
