# Generated by Django 4.1.5 on 2024-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0013_order_notified_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='test_field',
        ),
        migrations.AddField(
            model_name='order',
            name='box_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
