# Generated by Django 4.1.5 on 2024-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0014_remove_order_test_field_order_box_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test_field',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
