# Generated by Django 4.1.5 on 2025-07-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0012_remove_administrator_name'),
        ('app_orders', '0015_order_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='washer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_washes.washer', verbose_name='Washer'),
            preserve_default=False,
        ),
    ]
