# Generated by Django 4.1.5 on 2025-07-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0013_carwash_percent_washers'),
        ('app_orders', '0016_order_washer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasherEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='app_orders.order')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_washes.washer')),
            ],
        ),
    ]
