# Generated by Django 4.1.5 on 2025-08-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_washes', '0015_alter_administrator_phone'),
        ('app_orders', '0017_washerearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='washer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_washes.washer', verbose_name='Washer'),
        ),
    ]
