# Generated by Django 5.2.7 on 2025-10-15 14:48

import django.core.validators
import django.db.models.deletion
import accounts.models.sms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('name', models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('director', 'Director')], primary_key=True, serialize=False, verbose_name='Role name')),
                ('user', models.ManyToManyField(related_name='roles', related_query_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=accounts.models.sms.generate_sms_code, validators=[accounts.models.sms.validate_code], verbose_name='Code')),
                ('type', models.CharField(choices=[('register', 'Registration Code'), ('confirm', 'Confirm Code')], verbose_name='SMS Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('expires_at', models.DateTimeField(default=accounts.models.sms.get_default_expires_at, verbose_name='Expiration date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Code',
                'verbose_name_plural': 'SMS Codes',
            },
        ),
    ]
