# Generated by Django 5.2.7 on 2025-10-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_car_wash',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='car_wash.carwash', verbose_name='Manager of car wash'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='roles',
            name='user',
            field=models.ManyToManyField(related_name='roles', related_query_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smscode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
