# Generated by Django 5.2.7 on 2025-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managed_car_wash',
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('client', 'Client'), ('washer', 'Washer'), ('manager', 'Manager'), ('director', 'Director')], primary_key=True, serialize=False, verbose_name='Role name'),
        ),
    ]
