# Generated by Django 5.2.7 on 2025-10-14 18:41


from django.db import migrations, models


def create_roles(apps, schema_editor):
    Roles = apps.get_model("accounts", "Roles")

    Roles.objects.bulk_create([
        Roles(name=role) for role, _ in Roles._meta.local_fields[0].choices
    ], ignore_conflicts=True)


def remove_roles(apps, schema_editor):
    Roles = apps.get_model("accounts", "Roles")
    Roles.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_remove_user_managed_car_wash_alter_roles_name'),
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles)
    ]
